<h3>Методом исключения Гаусса с контрольным столбцом</h3>

In [9]:
def gauss(a, b):   
    m, n = a.shape # Количество строк и столбцов матрицы a
   
     # j означает столбец
    l = np.zeros((n,n))
    for k in range(n - 1):          
        for i in range(k + 1, n):      
            l[i][k] = a[i][k] / a[k][k]  
            for j in range(m):           
                a[i][j] = a[i][j] - l[i][k] * a[k][j]

            b[i] = b[i] - l[i][k] * b[k]
        
    x = np.zeros(n)                                              
    x[n - 1] = b[n - 1] / a[n - 1][n - 1]  

    for i in range(n - 2, -1, -1):         
        for j in range(i + 1, n):
            b[i] -= a[i][j] * x[j]         
        x[i] = b[i] / a[i][i]

    return x

        
if __name__ == '__main__':            
    D = np.array([[2.1, -4.5, -2.0], [3.0, 2.5, 4.3], [-6.0, 3.5, 2.5]])
    C = np.array([[0.1, 0.0, 0.0], [0.0, 0.1, 0.0], [0.0, 0.0, 0.1]])
    b = [19.07, 3.21, -18.25]
    k = 6
    A = get_the_finished_matrix(k, D, C)  
    print(A)
    print(gauss(A, b)) 

[[ 2.7 -4.5 -2. ]
 [ 3.   3.1  4.3]
 [-6.   3.5  3.1]]
[ 1.86400743 -4.22781971  2.49400437]


In [8]:
import scipy

D = np.array([[2.1, -4.5, -2.0], [3.0, 2.5, 4.3], [-6.0, 3.5, 2.5]])
C = np.array([[0.1, 0.0, 0.0], [0.0, 0.1, 0.0], [0.0, 0.0, 0.1]])
b = [19.07, 3.21, -18.25]
k = 6
B = get_the_finished_matrix(k, D, C)  
print(B)

scipy.linalg.solve(B, b)

[[ 2.7 -4.5 -2. ]
 [ 3.   3.1  4.3]
 [-6.   3.5  3.1]]


array([ 1.86400743, -4.22781971,  2.49400437])

In [4]:
def get_the_finished_matrix(scalar, D, C):
    n = len(C)
    numrows = len(C)   
    numcols = len(C[0])
    
    for numrow in range(numrows):
        for numkol in range(numcols):
            C[numrow][numkol] = round(scalar*C[numrow][numkol], 2)
    
    A = D + C
    return A